import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from 'next/link'

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "WordChat v0.1",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >    <div className="min-h-screen flex flex-col">
              <nav className="bg-primary text-primary-foreground p-4 fixed top-0 left-0 right-0 z-50">
                <div className="container mx-auto flex justify-between items-center">
                  <Link href="/" className="text-2xl font-bold">WordChat</Link>
                  <div className="flex gap-4">
                    <Link href="/config" className="hover:underline">Config</Link>
                  </div>
                </div>
              </nav>
              <div className="pt-16"> {/* Add padding to prevent content from being hidden behind the navbar */}
                {children}
              </div>
            </div>
      </body>
    </html>
  );
}
